"""
Software Development Kit used by the tool- and workflow scripts that are
generated by the transpiler.
"""

from __future__ import annotations

import js2py
import json
import os
import shutil
import stat
import yaml

from argparse import ArgumentParser, Namespace
from dask import delayed
from glob import glob as globglob
from itertools import product
from pathlib import Path
from uuid import uuid4

from typing import (
    Any,
    Iterator,
    Mapping,
    MutableMapping,
    Optional,
    Sequence,
    Union,
)

from cwl_utils.parser.cwl_v1_2 import File as CWLFile
from cwl_utils.parser.cwl_v1_2 import Directory as CWLDirectory

    
@delayed
def first_non_null(sources: list):
    """
    For the first level of a list input, pick the first non-null element. The
    result is a scalar. It is an error if there is no non-null element.

    # Examples:
    [null, x, null, y] -> x \n
    [null, [null], null, y] -> [null] \n
    [null, null, null] -> Runtime Error
    """
    for s in sources:
        if isinstance(s, list):
            if len(s) != 0 and s[0] is not None:
                return s
        elif s is not None:
            return s
    raise Exception("Sources contain no non-null element: ", sources)


@delayed
def the_only_non_null(sources: list):
    """
    For the first level of a list input, pick the single non-null element. The
    result is a scalar. It is an error if there is more than one non-null 
    element.

    # Examples:
    [null, x, null] -> x \n
    [null, x, null, y] -> Runtime Error \n
    [null, [null], null] -> [null] \n
    [null, null, null] -> Runtime Error
    """
    none_count = sources.count(None)
    n_sources = len(sources)
    if none_count == n_sources:
        raise Exception("Sources only contain null elements: ", sources)
    if none_count < n_sources - 1:
        raise Exception("Sources contain more than 1 non-null element: ", sources)
    
    for s in sources: 
        if s: 
            return s


@delayed
def all_non_null(sources: list):
    """
    For the first level of a list input, pick all non-null values. The result
    is a list, which may be empty.

    # Examples:
    [null, x, null] -> [x] \n
    [x, null, y] -> [x, y] \n
    [null, [x], [null]] -> [[x], [null]] \n
    [null, null, null] -> []
    """
    return [s for s in sources if s]


@delayed
def merge_nested(*sources):
    """
    The input must be an array consisting of exactly one entry for each input 
    link. If "merge_nested" is specified with a single link, the value from the
    link must be wrapped in a single-item list.
    """
    return [*sources]

@delayed
def merge_flattened(*sources):
    """
    The source and sink parameters must be compatible types, or the source type
    must be compatible with single element from the "items" type of the
    destination array parameter.
    Source parameters which are arrays are concatenated. Source parameters 
    which are single element types are appended as single elements.
    """
    ret = []
    for s in sources:
        if isinstance(s, list):
            ret.extend(s)
        else:
            ret.append(s)
    return ret


def js_eval(
        expression: str,
        context: Optional[dict[str, Any]] = None,
        requirement: Optional[Sequence] = None
    ) -> Any:
    """
    Evaluate a Javascript expression and return the result. A ``context`` of
    name-object pairs can be supplied, after which the names can be used as
    variables in the expression.

    CWL processes may have the InlineJavascriptRequirement, which may contain
    Javascript code that should be executed by the JS engine before evaluation
    takes place. Such code can be provided with ``requirement``, which expects
    a list of JS statements.
    """
    if context:
        context_vars = context.copy()
    else:
        context_vars = {}

    # 'self' is null by default.
    if "self" not in context_vars:
        context_vars["self"] = None

    # Initialize JS engine with context
    js_context = js2py.EvalJs(context_vars)

    # InlineJavascriptRequirement may contain JS code that must be
    # executed before the expressions evaluated. This JS code can then
    # be referenced in JS expressions.
    if requirement:
        for line in requirement:
            js_context.execute(line)

    # Evaluate expression
    result = js_context.eval(expression)

    if isinstance(result, js2py.base.JsObjectWrapper):
        # NOTE: https://github.com/PiotrDabkowski/Js2Py/blob/master/js2py/base.py#L1248
        # See link on how to check for array type.
        # TODO Support more types, like dict. How to handle custom
        # types?
        if result._obj.Class in ('Array', 'Int8Array', 'Uint8Array', # type: ignore
                            'Uint8ClampedArray', 'Int16Array',
                            'Uint16Array', 'Int32Array', 'Uint32Array',
                            'Float32Array', 'Float64Array', 'Arguments'):
            result = result.to_list()
    
    return result


def load_input_object(yaml_path):
    """
    Load the input object with values from a yaml. Special datatypes like
    files and directories are converted to their respective equivalents.
    """
    with open(yaml_path, "r") as f:
        input_yaml = yaml.load(f, Loader=yaml.BaseLoader)
        for k, v in input_yaml.items():
            if isinstance(v, dict):
                if hasattr(v, "class"):
                    if "file" in v["class"].lower():
                        input_yaml[k] = FileObject(v)
                    elif "directory" in v["class"].lower():
                        input_yaml[k] = DirectoryObject(v)
            elif isinstance(v, list):
                if len(v) == 0:
                    continue
                if "file" in v[0]["class"].lower():
                    input_yaml[k] = [FileObject(i) for i in v]
                elif "directory" in v[0]["class"].lower():
                    input_yaml[k] = [DirectoryObject(i) for i in v]
        return input_yaml
                


def scatterizer(
        inputs: dict, 
        keys: str | list[str],
        scatter_method: str = "dotproduct"
    ) -> Iterator[dict]:
    """
    Return a generator that creates copies of the inputs where
    the iterable scatter input arrays are replaced with scattered input items.
    """
    if isinstance(keys, str):
        keys = [keys]
    # Create an iterator that yields scatterized input combinations 
    arrays = [inputs[k] for k in keys]
    if scatter_method == "dotproduct":
        iterable = zip(*arrays)
    else:
        iterable = product(*arrays)

    # Copy the runtime_context and substitute the scattered inputs
    for values in iterable:
        inputs_copy = inputs.copy()
        for key, value in zip(keys, values):
            inputs_copy[key] = value
        yield inputs_copy


def transpose(list_of_dicts: list[dict]) -> dict[list]:
    """
    Transform a list of homogeneous dicts to a dict of lists. 
    """
    return {k: [dic[k] for dic in list_of_dicts] 
            for k in list_of_dicts[0]}


def glob(pattern: str | list[str]) -> list:
    """
    Takes one or more patterns and returns a list of all matched files and
    directories. This is a helper function that wraps `glob.glob` to allow
    searching for multiple patterns per call. 
    """
    if isinstance(pattern, str):
        return globglob(pattern)
    elif isinstance(pattern, list):
        matches = []
        for p in pattern:
            matches.extend(globglob(p))
    raise TypeError("'pattern' must be 'str' or 'list[str]', but found", type(pattern))


class FileObject:
    """
    Object that stores path properties as strings.
    Available properties: 
        path     : absolute/path/to/file.ext,
        basename : file.ext,
        dirname  : path/to,
        nameroot : file,
        nameext  : .ext

    TODO contents/size
    TODO location prefixes (file://, http://, https://)
    """
    attrs = [
        "location", "path", "basename", "dirname", "nameroot", "nameext",
        "contents", "size", "writable"
    ]

    location: str
    path: str
    basename: str
    dirname: str
    nameroot: str
    nameext: str
    contents: str
    size: int
    writable: bool
    # MAX_SIZE: int = 64000
    
    def __init__(
            self, 
            file_path: str | Path | FileObject | CWLFile | Mapping,
            loadContents: bool = False
        ):
        
        def load(o: Any, attr: str):
            if hasattr(o, attr) and getattr(o, attr) is not None:
                setattr(self, attr, getattr(o, attr))

        self.location = ""
        self.path = ""
        self.basename = ""
        self.dirname = ""
        self.nameroot = ""
        self.nameext = ""
        self.contents = ""
        self.size = 0
        self.writable = False

        if isinstance(file_path, str):
            file_path = Path(file_path)
        
        if isinstance(file_path, Path):
            # path: Path = file_path.resolve() < BUG dont use
            # pathlib.Path.resolve resolves symlinks, which is unwanted
            # behaviour, as we are sometimes pointing to symlinks. Normalizing
            # the parent and adding the name part circumvents this.
            # path: Path = file_path.parent.resolve() / file_path.name
            self.set_path_attributes(file_path)
            self.location = self.path
            if loadContents:
                self.load_contents()
        elif isinstance(file_path, FileObject | CWLFile):
            load(file_path, "location")
            load(file_path, "path")
            if self.location == "" and self.path != "":
                self.location = self.path
            if self.path == "" and self.location != "":
                self.path = self.location
            self.set_path_attributes(self.path)
            load(file_path, "basename")
            load(file_path, "dirname")
            load(file_path, "nameroot")
            load(file_path, "nameext")
            load(file_path, "contents")
            load(file_path, "size")
            load(file_path, "writable")
            # TODO Enable?
            # if loadContents:
            #     self.load_contents()
        elif isinstance(file_path, MutableMapping):
            if ("location" in file_path and file_path["location"] != "" 
                and ("path" not in file_path or
                    ("path" in file_path and file_path["path"] == ""))):
                file_path["path"] = file_path["location"]
            if "path" in file_path:
                self.set_path_attributes(file_path["path"])
            for k, v in file_path.items():
                if k in self.attrs:
                    setattr(self, k, v)
            # TODO Enable?
            # if loadContents:
            #     self.load_contents()
        else:
            raise Exception(f"FileObject expects 'str' | 'Path' | 'FileObject | cwl_utils.parser.cwl_v1_2.File', but found '{type(file_path)}'")
        

    def set_path_attributes(self, path: str | Path) -> None:
            if isinstance(path, str):
                path = Path(path)
            # path: Path = file_path.resolve() < BUG dont use
            # pathlib.Path.resolve resolves symlinks, which is unwanted
            # behaviour, as we are sometimes pointing to symlinks. Normalizing
            # the parent and adding the name part circumvents this.
            path = path.parent.resolve() / path.name
            self.path = str(path)
            self.basename = path.name
            self.dirname = str(path.parent)
            self.nameroot = path.stem
            self.nameext = path.suffix 


    def resolve(self) -> FileObject:
        return FileObject(Path(self.path).resolve())
    

    def resolve_as_str(self) -> str:
        return str(Path(self.path).resolve())
    

    def exists(self) -> bool:
        return Path(self.path).exists()
    

    def copy(self, target: str | Path) -> None:
        if isinstance(target, str):
            target = Path(target)
        if not isinstance(target, Path):
            raise Exception(f"Expected 'str' or 'Path', but found {type(target)}")
        shutil.copy2(Path(self.path).resolve(), target)
        

    def link(self, target:  str | Path) -> None:
        if isinstance(target, str):
            target = Path(target)
        if not isinstance(target, Path):
            raise Exception(f"Expected 'str' or 'Path', but found {type(target)}")
        os.symlink(Path(self.path).resolve(), target)
    

    def create(self, contents: Optional[str] = None) -> None:
        with open(self.path, "w") as f:
            if contents is not None:
                f.write(contents)
                # if loadContents:  # TODO Needed?
                #     self.contents = contents
            elif hasattr(self, "contents"):
                f.write(self.contents)
            os.chmod(self.path, os.stat(self.path).st_mode | stat.S_IEXEC)

    def load_contents(self):
        with open(self.path) as f:
            self.contents = f.read()
            self.size = len(self.contents)


    def rebase(self, new_path: str | Path) -> None:
        self.set_path_attributes(new_path)


    def __str__(self) -> str:
        return self.path
    

    def to_dict(self) -> dict:
        return {k: getattr(self, k) 
                for k in self.attrs 
                if hasattr(self, k) and getattr(self, k) is not None}
    

    def __repr__(self) -> str:
        pairs = [f'"{k}":"{v}"' for k, v in self.to_dict().items()]
        return f"FileObject({{{', '.join(pairs)}}})"
    
    
class DirectoryObject:
    """
    Object that stores path properties as strings.
    Available properties: 
        location : TODO
        path     : absolute/path/to/file.ext,
        basename : file.ext,
        listing  : [sub-file?, sub-directory?]
    """
    # TODO handle listings?
    location: str   # TODO
    path: str
    basename: str
    listing: list[Union[FileObject, DirectoryObject]]
    attrs = ["location", "path", "basename", "listing"]
    
    def __init__(
            self,
            dir_path: str | Path | DirectoryObject | CWLDirectory | Mapping):

        def load(o: Any, attr: str):
            if hasattr(o, attr) and getattr(o, attr) is not None:
                setattr(self, attr, getattr(o, attr))

        self.location = ""
        self.path = ""
        self.basename = ""
        self.listing = []
        
        if isinstance(dir_path, str):
            dir_path = Path(dir_path)

        if isinstance(dir_path, Path):
            # path: Path = dir_path.resolve() < BUG 
            # pathlib.Path.resolve resolves symlinks, which is unwanted
            # behaviour, as we are sometimes pointing to symlinks. Normalizing
            # the parent and adding the name part circumvents this.
            path: Path = dir_path.parent.resolve() / dir_path.name
            self.set_path_attributes(path)
            self.location = self.path
            # NOTE Does this need to be recursive? 
            for p in path.iterdir():
                if p.is_dir():
                    self.listing.append(DirectoryObject(str(p)))
                if p.is_file():
                    self.listing.append(FileObject(str(p)))
        elif isinstance(dir_path, DirectoryObject | CWLDirectory):
            load(dir_path, "location")
            load(dir_path, "path")
            if self.location == "" and self.path != "":
                self.location = self.path
            if self.path == "" and self.location != "":
                self.path = self.location
            self.set_path_attributes(self.path)
            load(dir_path, "basename")
            load(dir_path, "listing")
        elif isinstance(dir_path, MutableMapping):
            if ("location" in dir_path and dir_path["location"] != "" 
                and ("path" not in dir_path or 
                    ("path" in dir_path and dir_path["path"] == ""))):
                dir_path["path"] = dir_path["location"]
            if "path" in dir_path:
                self.set_path_attributes(dir_path["path"])
            for k, v in dir_path.items():
                if k in self.attrs:
                    setattr(self, k, v)
        else:
            raise Exception(f"DirectoryObject expects 'str' | 'Path' | 'DirectoryObject', but found '{type(dir_path)}'")
        

    def set_path_attributes(self, path: str | Path) -> None:
            if isinstance(path, str):
                path = Path(path)
            self.path = str(path)
            self.basename = path.name


    def resolve(self) -> DirectoryObject:
        return DirectoryObject(Path(self.path).resolve())
    

    def resolve_as_str(self) -> str:
        return str(Path(self.path).resolve())
    

    def exists(self) -> bool:
        return Path(self.path).exists()
    

    def copy(self, target: str | Path) -> None:
        if isinstance(target, str):
            target = Path(target)
        if not isinstance(target, Path):
            raise Exception(f"Expected 'str' or 'Path', but found {type(target)}")
        shutil.copytree(Path(self.path).resolve(), target, symlinks=False)  #TODO copy symlinks?


    def link(self, target: str | Path) -> None:
            if isinstance(target, str):
                target = Path(target)
            if not isinstance(target, Path):
                raise Exception(f"Expected 'str' or 'Path', but found {type(target)}")
            os.symlink(Path(self.path).resolve(), target, target_is_directory=True)


    def create(self) -> None:
        Path(self.path).mkdir(parents = True)


    def rebase(self, new_path: str | Path) -> None:
        self.set_path_attributes(new_path)


    def __str__(self) -> str:
        return self.path
    

    def __repr__(self) -> str:
        pairs = [f'"{k}":"{getattr(self, k)}"' 
                 for k in self.attrs 
                 if hasattr(self, k) and getattr(self, k) is not None]
        return f"DirectoryObject({', '.join(pairs)})"

    

def process_cli_args() -> tuple[dict, dict[str, str], bool]:
    """
    
    """
    parser = ArgumentParser()
    parser.add_argument(
        "input_object",
        type=str,
        help="Path to the YAML file that contains the input object to this process."
    )
    parser.add_argument(
        "--outdir",
        default = os.getcwd(),
        type = str,
        help = "Directory to store output files in."
    )
    parser.add_argument(
        "--tmpdir",
        type = str,
        default = "/tmp/" + str(uuid4()),
        help="Directory to store temporary files in."
    )
    parser.add_argument(
        "--leave_tmpdir",
        action="store_true",
        default = False,
        help="Preserve temporary files and directories created for tool execution instead of deleting them."
    )

    env = {}
    args = parser.parse_args()

    # Check input object path validity
    if not Path(args.input_object).resolve().is_file():
            raise FileNotFoundError(f"{args.input_object} does not exist or is not a file")

    # Configure designated output directory
    out_dir_path = Path(args.outdir).resolve()
    if out_dir_path.exists() and not out_dir_path.is_dir():
        raise Exception(f"{out_dir_path} is not a directory")
    out_dir_path.mkdir(parents=True, exist_ok=True)  # Create out dir if needed
    env["HOME"] = str(out_dir_path)
    # env["HOME"] = out_dir_path

    # Configure designated temporary directory
    tmp_dir_path = Path(args.tmpdir).resolve()
    if tmp_dir_path.exists() and not tmp_dir_path.is_dir():
        raise Exception(f"{tmp_dir_path} is not a directory")
    if tmp_dir_path.exists() and any(tmp_dir_path.iterdir()):
        raise Exception(f'{tmp_dir_path} must be empty!')
    tmp_dir_path.mkdir(parents=True, exist_ok=True)  # Create tmp dir if needed
    env["TMPDIR"] = str(tmp_dir_path)
    # env["TMPDIR"] = tmp_dir_path

    env["PATH"] = os.getenv("VIRTUAL_ENV") + "/bin:" + os.getenv("PATH")
    # env["PYTHONPATH"] = sys.executable + ":" + env["PATH"]
    env["VIRTUAL_ENV"] = os.getenv("VIRTUAL_ENV")
    # print(os.getenv("VIRTUAL_ENV"))
    # exit()

    return load_input_object(args.input_object), env, args.leave_tmpdir


def checkout(env: dict) -> Path:
    """
    Create a new temporary directory and set it as the current working 
    directory. The new directory is created by taking `env["TMPDIR"]` and 
    appending a random uuid generated with `uuid.uuid4()`. `env["PATH"]` is
    prepended with the new path.

    Returns:
        `Path` to the new current working directory.
    """
    tmp_path: Path = Path(env["TMPDIR"]) / str(uuid4())
    env["PATH"] = str(tmp_path) + ":" + env["PATH"]
    tmp_path.mkdir()
    os.chdir(tmp_path)

    return tmp_path


def initial_work_dir_requirement(listing: list | Mapping | FileObject | DirectoryObject | CWLFile | CWLDirectory | None) -> None:
    """
    Stage files and directories from a CWL InitialWorkDirRequirement listing
    into the current working directory.

    The listing may be either:
      - a dirent in the form of a dict with keys 'entry' and optional
        'entryname'
      - a FileObject or CWLFile
      - a DirectoryObject or CWLDirectory
      - None
      - or a list containing any of the above

    This function normalizes non-list inputs to a list and then proceeds to
    stage entries into Path.cwd(). Expressions are assumed to have been
    evaluated by the caller, and iteration proceeds in-order (no reversed
    popping).
    """
    import json

    cwd = Path.cwd()

    # Normalize input to a list
    if listing is None:
        return
    if isinstance(listing, (FileObject, DirectoryObject, CWLFile, CWLDirectory)):
        listing = [listing]
    elif isinstance(listing, Mapping):
        # Single dirent mapping or single File/Directory map
        listing = [listing]
    elif not isinstance(listing, list):
        raise TypeError("'listing' must be a dirent dict, FileObject, DirectoryObject, CWLFile, CWLDirectory, None, or a list of these")

    # Flatten nested lists
    while any(isinstance(x, list) for x in listing):
        for idx, item in enumerate(listing.copy()):
            if isinstance(item, list):
                # replace the list element with its contents
                listing[idx:idx+1] = item
                break

    # Process entries in order. Build a list of items to stage.
    staged: list = []
    for l in listing:
        # Handle dirent mappings (with 'entry')
        if isinstance(l, Mapping) and "entry" in l:
            entry = l["entry"]
            entryname = l.get("entryname", None)

            # null entries do nothing
            if entry is None:
                continue

            # If the entry is a list, it may be file literal lines or a list
            # of files/directories.
            if isinstance(entry, list) and len(entry) > 0:
                first = entry[0]
                if isinstance(first, str):
                    # file literal: join lines
                    if entryname is None:
                        raise Exception("Dirent with file literal must have an entryname")
                    contents = "\n".join(entry)
                    entry_path = (cwd / Path(entryname)).resolve()
                    if os.path.commonpath([str(cwd.resolve()), str(entry_path)]) != str(cwd.resolve()):
                        raise Exception("Must create file/directory within working folder")
                    FileObject(entry_path).create(contents)
                    continue
                else:
                    # list of files/directories: add them to staged list
                    staged.extend(entry)
                    continue

            # If entry is a mapping describing a File/Directory, or an SDK/CWL
            # File/Directory object, stage it.
            if isinstance(entry, Mapping) and "class" in entry:
                staged.append(entry)
                continue
            if isinstance(entry, (FileObject, DirectoryObject, CWLFile, CWLDirectory)):
                staged.append(entry)
                continue

            # If entry is a string, treat it as a file literal with single
            # line content
            if isinstance(entry, str):
                if entryname is None:
                    raise Exception("Dirent with file literal must have an entryname")
                contents = entry
                entry_path = (cwd / Path(entryname)).resolve()
                if os.path.commonpath([str(cwd.resolve()), str(entry_path)]) != str(cwd.resolve()):
                    raise Exception("Must create file/directory within working folder")
                FileObject(entry_path).create(contents)
                continue

            # Otherwise, serialize to JSON and create the file
            if entryname is None:
                raise Exception("Dirent with file literal must have an entryname")
            contents = json.dumps(entry, indent=4)
            entry_path = (cwd / Path(entryname)).resolve()
            if os.path.commonpath([str(cwd.resolve()), str(entry_path)]) != str(cwd.resolve()):
                raise Exception("Must create file/directory within working folder")
            FileObject(entry_path).create(contents)
            continue

        # Non-dirent entries are appended for staging
        staged.append(l)

    # Convert any remaining map-form File/Directory entries to objects
    for idx, item in enumerate(staged):
        if isinstance(item, Mapping) and "class" in item:
            if "File" in item["class"]:
                staged[idx] = FileObject(item)
            elif "Directory" in item["class"]:
                staged[idx] = DirectoryObject(item)

    # Also convert any remaining CWLFile / CWLDirectory entries to SDK objects
    for idx, item in enumerate(staged):
        if isinstance(item, CWLFile):
            staged[idx] = FileObject(item)
        elif isinstance(item, CWLDirectory):
            staged[idx] = DirectoryObject(item)

    # Stage remaining FileObject and DirectoryObject entries into cwd
    for obj in staged:
        if obj is None:
            continue
        if isinstance(obj, FileObject):
            target = cwd / obj.basename
            # If source exists, either copy (writable) or link (read-only)
            if obj.exists():
                if getattr(obj, "writable", False):
                    obj.copy(target)
                else:
                    obj.link(target)
            else:
                # Create a new file at the target path using the object's
                # contents/attributes
                obj.rebase(target)
                obj.create()
        elif isinstance(obj, DirectoryObject):
            target = cwd / obj.basename
            if obj.exists():
                obj.copy(target)
            else:
                obj.rebase(target)
                obj.create()
            # Note: DirectoryObject.listing staging is not implemented
        else:
            raise Exception(f"Expected 'dict', 'FileObject' or 'DirectoryObject', but found '{type(obj)}'")

def finalize(
        outputs: dict[str, Any],
        env: dict,
        preserve_tmpdir: bool,
        verbose: bool = False
    ) -> str:
    """
    Copy the output files to the designated output directory and return a
    JSON string containing the outputs.
    """
    copy_alert = True
    new_outputs: dict[str, Any] = {}
    for id, output in outputs.items():
        if isinstance(output, (FileObject, DirectoryObject)):
            output = [output]

        if not isinstance(output, list):
            new_outputs[id] = output
            continue

        for o in output:
            if isinstance(o, (FileObject, DirectoryObject)):
                # Files and directories need to be moved to the output directory
                if copy_alert and verbose:
                    print("[PROCESS]: Moving output to designated output directory:")
                    copy_alert = False

                # Move the output to the output directory
                if verbose:
                    print(f"[PROCESS]:\t- {id}: {old_path} >> {new_path}")
                old_path = Path(o.path)
                new_path = shutil.move(old_path, env["HOME"])
                o.rebase(new_path)
                o = str(o)
            new_outputs[id] = o
    if not preserve_tmpdir:
        shutil.rmtree(env["TMPDIR"])
    return json.dumps(new_outputs, indent = 4)