"""
Software Development Kit used by the tool- and workflow scripts that are
generated by the transpiler.
"""

from __future__ import annotations

# import numpy as np
import js2py
import os
import shutil
import yaml

from glob import glob as globglob
from itertools import product
from pathlib import Path
# from math import prod

from typing import (
    Any,
    Iterator,
    Mapping,
    MutableMapping,
    Optional,
    Sequence,
    Union,
    # cast
)

from cwl_utils.parser.cwl_v1_2 import File as CWLFile
from cwl_utils.parser.cwl_v1_2 import Directory as CWLDirectory


def js_eval(
        expression: str,
        context: Optional[dict[str, Any]] = None,
        requirement: Optional[Sequence] = None
    ) -> Any:
    """
    
    """
    if context:
        context_vars = context.copy()
    else:
        context_vars = {}

    # 'self' is null by default.
    if "self" not in context_vars:
        context_vars["self"] = None

    # Initialize JS engine with context
    js_context = js2py.EvalJs(context_vars)

    # InlineJavascriptRequirement may contain JS code that must be
    # executed before the expressions evaluated. This JS code can then
    # be referenced in JS expressions.
    if requirement:
        for line in requirement:
            js_context.execute(line)

    # Evaluate expression
    result = js_context.eval(expression)

    if isinstance(result, js2py.base.JsObjectWrapper):
        # NOTE: https://github.com/PiotrDabkowski/Js2Py/blob/master/js2py/base.py#L1248
        # See link on how to check for array type.
        # TODO Support more types, like dict. How to handle custom
        # types?
        if result._obj.Class in ('Array', 'Int8Array', 'Uint8Array', # type: ignore
                            'Uint8ClampedArray', 'Int16Array',
                            'Uint16Array', 'Int32Array', 'Uint32Array',
                            'Float32Array', 'Float64Array', 'Arguments'):
            result = result.to_list()
    
    return result


def load_input_object(yaml_path):
    """
    Load the input object with values from a yaml. Special datatypes like
    files and directories are converted to their respective equivalents.
    """
    with open(yaml_path, "r") as f:
        input_yaml = yaml.load(f, Loader=yaml.BaseLoader)
        for k, v in input_yaml.items():
            if isinstance(v, dict):
                if hasattr(v, "class"):
                    if "file" in v["class"].lower():
                        input_yaml[k] = FileObject(v)
                    elif "directory" in v["class"].lower():
                        input_yaml[k] = DirectoryObject(v)
            elif isinstance(v, list):
                if len(v) == 0:
                    continue
                if "file" in v[0]["class"].lower():
                    input_yaml[k] = [FileObject(i) for i in v]
                elif "directory" in v[0]["class"].lower():
                    input_yaml[k] = [DirectoryObject(i) for i in v]
        return input_yaml
                


def scatterizer(
        inputs: dict, 
        keys: str | list[str],
        scatter_method: str = "dotproduct"
    ) -> Iterator:
    """
    Return a generator that creates copies of the inputs where
    the iterable scatter input arrays are replaced with scattered input items.
    """
    if isinstance(keys, str):
        keys = [keys]
    # Create an iterator that yields scatterized input combinations 
    arrays = [inputs[k] for k in keys]
    if scatter_method == "dotproduct":
        iterable = zip(*arrays)
    else:
        iterable = product(*arrays)

    # Copy the runtime_context and substitute the scattered inputs
    for values in iterable:
        inputs_copy = inputs.copy()
        for key, value in zip(keys, values):
            inputs_copy[key] = value
        yield inputs_copy

def transpose(list_of_dicts: list[dict]) -> dict[list]:
    """
    Transform a list of homogeneous dicts to a dict of lists. 
    """
    return {k: [dic[k] for dic in list_of_dicts] 
            for k in list_of_dicts[0]}

def glob(pattern: str | list[str]) -> list:
    """
    Takes one or more patterns and returns a list of all matches files and
    directories. This is a helper function that wraps `glob.glob` to allow
    searching for multiple patterns per call. 
    """
    if isinstance(pattern, str):
        return globglob(pattern)
    elif isinstance(pattern, list):
        matches = []
        for p in pattern:
            matches.extend(globglob(p))
    raise TypeError("'pattern' must be 'str' or 'list[str]', but found", type(pattern))


class FileObject:
    """
    Object that stores path properties as strings.
    Available properties: 
        path     : absolute/path/to/file.ext,
        basename : file.ext,
        dirname  : path/to,
        nameroot : file,
        nameext  : .ext

    TODO contents/size
    TODO location prefixes (file://, http://, https://)
    """
    attrs = [
        "location", "path", "basename", "dirname", "nameroot", "nameext",
        "contents", "size", "writable"
    ]

    location: str
    path: str
    basename: str
    dirname: str
    nameroot: str
    nameext: str
    contents: str
    size: int
    writable: bool
    # MAX_SIZE: int = 64000
    
    def __init__(
            self, 
            file_path: str | Path | FileObject | CWLFile | Mapping
        ):
        
        def load(o: Any, attr: str):
            if hasattr(o, attr) and getattr(o, attr) is not None:
                setattr(self, attr, getattr(o, attr))

        self.location = ""
        self.path = ""
        self.basename = ""
        self.dirname = ""
        self.nameroot = ""
        self.nameext = ""
        self.contents = ""
        self.size = 0
        self.writable = False

        if isinstance(file_path, str):
            file_path = Path(file_path)
        
        if isinstance(file_path, Path):
            # path: Path = file_path.resolve() < BUG dont use
            # pathlib.Path.resolve resolves symlinks, which is unwanted
            # behaviour, as we are sometimes pointing to symlinks. Normalizing
            # the parent and adding the name part circumvents this.
            # path: Path = file_path.parent.resolve() / file_path.name
            self.set_path_attributes(file_path)
            self.location = self.path
        elif isinstance(file_path, FileObject | CWLFile):
            load(file_path, "location")
            load(file_path, "path")
            if self.location == "" and self.path != "":
                self.location = self.path
            if self.path == "" and self.location != "":
                self.path = self.location
            self.set_path_attributes(self.path)
            load(file_path, "basename")
            load(file_path, "dirname")
            load(file_path, "nameroot")
            load(file_path, "nameext")
            load(file_path, "contents")
            load(file_path, "size")
            load(file_path, "writable")
        elif isinstance(file_path, MutableMapping):
            if ("location" in file_path and file_path["location"] != "" 
                and ("path" not in file_path or
                    ("path" in file_path and file_path["path"] == ""))):
                file_path["path"] = file_path["location"]
            if "path" in file_path:
                self.set_path_attributes(file_path["path"])
            for k, v in file_path.items():
                if k in self.attrs:
                    setattr(self, k, v)
        else:
            raise Exception(f"FileObject expects 'str' | 'Path' | 'FileObject | cwl_utils.parser.cwl_v1_2.File', but found '{type(file_path)}'")
        

    def set_path_attributes(self, path: str | Path) -> None:
            if isinstance(path, str):
                path = Path(path)
            # path: Path = file_path.resolve() < BUG dont use
            # pathlib.Path.resolve resolves symlinks, which is unwanted
            # behaviour, as we are sometimes pointing to symlinks. Normalizing
            # the parent and adding the name part circumvents this.
            path = path.parent.resolve() / path.name
            self.path = str(path)
            self.basename = path.name
            self.dirname = str(path.parent)
            self.nameroot = path.stem
            self.nameext = path.suffix 


    def resolve(self) -> FileObject:
        return FileObject(Path(self.path).resolve())
    

    def resolve_as_str(self) -> str:
        return str(Path(self.path).resolve())
    

    def exists(self) -> bool:
        return Path(self.path).exists()
    

    def copy(self, target: str | Path) -> None:
        if isinstance(target, str):
            target = Path(target)
        if not isinstance(target, Path):
            raise Exception(f"Expected 'str' or 'Path', but found {type(target)}")
        shutil.copy2(Path(self.path).resolve(), target)
        

    def link(self, target:  str | Path) -> None:
        if isinstance(target, str):
            target = Path(target)
        if not isinstance(target, Path):
            raise Exception(f"Expected 'str' or 'Path', but found {type(target)}")
        os.symlink(Path(self.path).resolve(), target)
    

    def create(self, contents: Optional[str] = None) -> None:
        with open(self.path, "w") as f:
            if contents is not None:
                f.write(contents)
                # if loadContents:  # TODO Needed?
                #     self.contents = contents
            elif hasattr(self, "contents"):
                f.write(self.contents)


    def rebase(self, new_path: str | Path) -> None:
        self.set_path_attributes(new_path)


    def __str__(self) -> str:
        return self.path
    

    def to_dict(self) -> dict:
        return {k: getattr(self, k) 
                for k in self.attrs 
                if hasattr(self, k) and getattr(self, k) is not None}
    

    def __repr__(self) -> str:
        pairs = [f'"{k}":"{getattr(self, k)}"' 
                 for k in self.attrs 
                 if hasattr(self, k) and getattr(self, k) is not None]
        return f"FileObject({', '.join(pairs)})"
    
    
class DirectoryObject:
    """
    Object that stores path properties as strings.
    Available properties: 
        location : TODO
        path     : absolute/path/to/file.ext,
        basename : file.ext,
        listing  : [sub-file?, sub-directory?]
    """
    # TODO handle listings?
    location: str   # TODO
    path: str
    basename: str
    listing: list[Union[FileObject, DirectoryObject]]
    attrs = ["location", "path", "basename", "listing"]
    
    def __init__(
            self,
            dir_path: str | Path | DirectoryObject | CWLDirectory | Mapping):

        def load(o: Any, attr: str):
            if hasattr(o, attr) and getattr(o, attr) is not None:
                setattr(self, attr, getattr(o, attr))

        self.location = ""
        self.path = ""
        self.basename = ""
        self.listing = []
        
        if isinstance(dir_path, str):
            dir_path = Path(dir_path)

        if isinstance(dir_path, Path):
            # path: Path = dir_path.resolve() < BUG 
            # pathlib.Path.resolve resolves symlinks, which is unwanted
            # behaviour, as we are sometimes pointing to symlinks. Normalizing
            # the parent and adding the name part circumvents this.
            path: Path = dir_path.parent.resolve() / dir_path.name
            self.set_path_attributes(path)
            self.location = self.path
            # NOTE Does this need to be recursive? 
            for p in path.iterdir():
                if p.is_dir():
                    self.listing.append(DirectoryObject(str(p)))
                if p.is_file():
                    self.listing.append(FileObject(str(p)))
        elif isinstance(dir_path, DirectoryObject | CWLDirectory):
            load(dir_path, "location")
            load(dir_path, "path")
            if self.location == "" and self.path != "":
                self.location = self.path
            if self.path == "" and self.location != "":
                self.path = self.location
            self.set_path_attributes(self.path)
            load(dir_path, "basename")
            load(dir_path, "listing")
        elif isinstance(dir_path, MutableMapping):
            if ("location" in dir_path and dir_path["location"] != "" 
                and ("path" not in dir_path or 
                    ("path" in dir_path and dir_path["path"] == ""))):
                dir_path["path"] = dir_path["location"]
            if "path" in dir_path:
                self.set_path_attributes(dir_path["path"])
            for k, v in dir_path.items():
                if k in self.attrs:
                    setattr(self, k, v)
        else:
            raise Exception(f"DirectoryObject expects 'str' | 'Path' | 'DirectoryObject', but found '{type(dir_path)}'")
        

    def set_path_attributes(self, path: str | Path) -> None:
            if isinstance(path, str):
                path = Path(path)
            self.path = str(path)
            self.basename = path.name


    def resolve(self) -> DirectoryObject:
        return DirectoryObject(Path(self.path).resolve())
    

    def resolve_as_str(self) -> str:
        return str(Path(self.path).resolve())
    

    def exists(self) -> bool:
        return Path(self.path).exists()
    

    def copy(self, target: str | Path) -> None:
        if isinstance(target, str):
            target = Path(target)
        if not isinstance(target, Path):
            raise Exception(f"Expected 'str' or 'Path', but found {type(target)}")
        shutil.copytree(Path(self.path).resolve(), target, symlinks=False)  #TODO copy symlinks?


    def link(self, target: str | Path) -> None:
            if isinstance(target, str):
                target = Path(target)
            if not isinstance(target, Path):
                raise Exception(f"Expected 'str' or 'Path', but found {type(target)}")
            os.symlink(Path(self.path).resolve(), target, target_is_directory=True)


    def create(self) -> None:
        Path(self.path).mkdir(parents = True)


    def rebase(self, new_path: str | Path) -> None:
        self.set_path_attributes(new_path)


    def __str__(self) -> str:
        return self.path
    

    def __repr__(self) -> str:
        pairs = [f'"{k}":"{getattr(self, k)}"' 
                 for k in self.attrs 
                 if hasattr(self, k) and getattr(self, k) is not None]
        return f"DirectoryObject({', '.join(pairs)})"
    